### PR TITLE
add image scaling

### PR DESCRIPTION
**Pull request by comalnik**

### CODE REVIEW

**Comment by FluffyBeanAce** [comment]
> 

Would you think it would be possible to create a new function in a file named image.py instead of only modify ?

**Comment by comalnik** [comment]
So i would need to make a file "image.py" and put the image upscale function in there, and then call it from main?

**Comment by FluffyBeanAce** [comment]
> So i would need to make a file "image.py" and put the image upscale function in there, and then call it from main?

If you think it is logic to do, yes. If not, keep it in def_func.py

**Comment by comalnik** [comment]
I dont think its worth creating a new file for just one function, but i can make a separate image upscaling function in def_func.py
And then we can move it to image.py if we add more image processing

**Comment by FluffyBeanAce** [comment]
Sounds perfect!. I'm going to merge it after the change (creating a new function)

**Comment by comalnik** [comment]
Great, its done now.

**Review by FluffyAceBean — APPROVED** [review]

**Pull request merged**
